- app.yaml
Increases memory to 16GB (and sets storage to this too).
> Increase memory

- Dockerfile
Final attempt before I revert to the working version.
> Increase timeout

- Dockerfile
- Makefile
Avoids running the test suite twice on the Docker instance (~3 mins).
> Action performance improvements

- policyengine/server.py
- setup.py
Also increases the cache version.
> Bump version

- policyengine/countries/uk/reform_parameters.yaml
- policyengine/server.py
> Add Council Tax abolition test

- policyengine/countries/country.py
- policyengine/impact/population/breakdown.py
- policyengine/utils/reforms.py
> Fix population breakdown bug

- policyengine-client/src/common/parameter.jsx
- policyengine/__init__.py
- policyengine/countries/uk/default_reform.py
- policyengine/countries/uk/reform_parameters.yaml
Aesthetic changes.
Currently a draft because I made some of the descriptions match the label. In some sense this might be goofier than the slightly less concise rephrasings currently in the app, but I'm not sure it's by much. It'd be better to add some more actual information to the descriptions to justify their prominence. Though reviewing all the similarities to labels pushes me back to hiding descriptions (and other information) behind tooltips--removing the descriptions could free up a lot of space and make the app look considerably cleaner.
> Edit parameter and variable labels

- policyengine/countries/country.py
> Fix breakdown bug

- policyengine-client/src/common/url.jsx
> Fix abolition bug

- policyengine-client/src/countries/us/data/situation.jsx
- setup.py
Draft, to preview SNAP additions to the household input page
> Add SNAP variables

- policyengine-client/src/common/pages/household.jsx
> Fix React code style error

- policyengine/utils/charts.py
> Use a solid zero line

- policyengine-client/src/countries/uk/data/policy.jsx
- policyengine/__init__.py
- policyengine/countries/uk/default_reform/reform.py
- policyengine/countries/uk/reform_parameters.yaml
- policyengine/utils/reforms.py
- setup.py
* LVT split for corporations and households
* CB HITC/PA reduction/Marriage allowance parameters surfaced
* SDLT/LTT/LBTT added
> Updates to property taxes and tax reliefs

- .github/has-functional-changes.sh
- .github/is-version-number-acceptable.sh
- .github/publish-git-tag.sh
- .github/workflows/pr.yml
- .github/workflows/push.yml
- CHANGELOG.md
- policyengine-client/package.json
- policyengine-client/src/policyengine/pages/policy/overview.jsx
- policyengine-client/src/policyengine/pages/populationImpact/populationImpact.jsx
- policyengine-client/src/policyengine/policyengine.jsx
- policyengine-client/src/policyengine/tools/namedPolicies.jsx
- policyengine/__init__.py
* Adds semantic version checks and a changelog with this PR.
* Fixes #342 
* Fixes #336
> Fix URL bugs

- CHANGELOG.md
- README.md
- policyengine-client/package.json
- policyengine-client/src/countries/country.jsx
- policyengine-client/src/countries/uk/uk.jsx
- policyengine-client/src/countries/us/us.jsx
- policyengine/__init__.py
Adds the local debugging option.
> Local debugging

- CHANGELOG.md
- policyengine-client/package.json
- policyengine-client/src/countries/country.jsx
- policyengine-client/src/countries/uk/uk.jsx
- policyengine-client/src/policyengine/pages/policy/parameter.jsx
- policyengine/__init__.py
Fixes #250 
Fixes #249 
Fixes #251
> Add allowances

- CHANGELOG.md
- Makefile
- README.md
- policyengine/__init__.py
- policyengine/countries/country.py
- policyengine/countries/uk/__init__.py
- policyengine/server.py
- policyengine/tests/server/populations/test_population_charts.py
- setup.py
* Command-line flag added for using synthetic UK data for debugging.
* OpenFisca-UK version updated to 0.10.5.
* OpenFisca-US version updated to 0.23.1.
@tolaouk @MaxGhenis  this should hopefully fix the UK synthetic issue.
> Add synthetic flag

- CHANGELOG.md
- policyengine-client/src/policyengine/pages/populationImpact/populationImpact.jsx
- policyengine/__init__.py
- policyengine/countries/country.py
- policyengine/impact/population/charts.py
* Inequality chart showing relative change to the Gini coefficient and top-10% and top-1% income shares.
> Inequality chart

- CHANGELOG.md
- policyengine-client/package.json
- policyengine-client/src/countries/country.jsx
- policyengine-client/src/countries/uk/uk.jsx
- policyengine-client/src/policyengine/pages/household/inputPane.jsx
- policyengine-client/src/policyengine/tools/translation.jsx
- policyengine/__init__.py
- policyengine/impact/population/charts.py
- policyengine/server.py
- policyengine/utils/situations.py
* Adds stocks/flows metadata
* Reorganises the household page to Household/ and Personal/
> Add stocks/flow metadata and reorganise

- CHANGELOG.md
- policyengine-client/package.json
- policyengine-client/src/countries/country.jsx
- policyengine-client/src/policyengine/pages/policy/overview.jsx
- policyengine-client/src/policyengine/pages/populationImpact/populationImpact.jsx
- policyengine/__init__.py
Fixes #332 
Fixes #333
Fixes #334 
Fixes #335
> fix ui changes

- CHANGELOG.md
- policyengine-client/package.json
- policyengine-client/public/index.html
- policyengine-client/src/countries/us/us.jsx
- policyengine-client/src/policyengine/pages/household/variable.jsx
- policyengine-client/src/policyengine/policyengine.jsx
- policyengine/__init__.py
- policyengine/impact/population/charts.py
- setup.py
Fixes #402, fixes #405
Requires https://github.com/PolicyEngine/openfisca-us/pull/507
> Add school meals and net income breakdown

- README.md
Short description of the changes made.
> Update README with python version requirement

- .github/workflows/push.yml
> Remove duplicate add commit

- .github/get-changelog-diff.sh
- .github/workflows/push.yml
- changelog.yaml
Ensures the PR actually previews correctly
> Fix PR preview action

- changelog.yaml
- setup.py
@tolaouk @yuantaoz nearly there! Just this last PR
> Bump OpenFisca-UK

- changelog.yaml
- policyengine-client/src/countries/us/us.jsx
Fixes #649
Pending some broader work in openfisca-us.
I tested this locally and it works. I also tested that adjusting dividend and interest income appropriately changes both taxes and benefits.
> Remove US self-employment income input

- changelog.yaml
- policyengine-client/src/countries/country.jsx
- policyengine-client/src/policyengine/general/help.jsx
- policyengine-client/src/policyengine/general/navigationButton.jsx
- policyengine-client/src/policyengine/pages/household/household.jsx
- policyengine-client/src/policyengine/pages/policy/policy.jsx
- policyengine-client/src/policyengine/pages/populationImpact/populationImpact.jsx
- policyengine/countries/uk/__init__.py
- policyengine/countries/uk/default_reform/reform.py
- setup.py
* Bump OpenFisca US to bring in CTC bug fix
* Fixes #647 (doesn't work yet, see screenshot below)
> Bump OpenFisca US and fit navigation buttons to width

- changelog.yaml
- policyengine/impact/household/charts.py
> Fix US `How earnings affect you` chart

- changelog.yaml
- policyengine-client/src/landing.jsx
> Fix blog posts

- changelog.yaml
- policyengine/countries/us/__init__.py
- policyengine/tests/server/initialisation.py
- setup.py
Should enable deployment again.
> US microsimulation

- changelog.yaml
- policyengine-client/src/countries/country.jsx
- policyengine-client/src/policyengine/pages/legislationExplorer.jsx
- policyengine/countries/us/__init__.py
- policyengine/utils/reforms.py
- policyengine/utils/situations.py
> Add references to the legislation explorer

- changelog.yaml
- policyengine-client/src/policyengine/pages/apiExplorer.jsx
- policyengine-client/src/policyengine/policyengine.jsx
* Adds redirects from /legislation
> Rename legislation-explorer to API explorer

- changelog.yaml
- policyengine-client/src/policyengine/pages/apiExplorer.jsx
- policyengine/utils/situations.py
Fixes #684 
Fixes #691 
Fixes #689
> Add features

- changelog.yaml
- setup.py
> Fix NI thresholds pre-July

- changelog.yaml
- policyengine-client/src/countries/uk/uk.jsx
> Fix geographic break

- changelog.yaml
- policyengine-client/src/policyengine/pages/apiExplorer.jsx
- policyengine/utils/reforms.py
- setup.py
Requires https://github.com/PolicyEngine/openfisca-uk/pull/610
> Add more references

- changelog.yaml
Short description of the changes made.
List any issues fixed here.
> Bump openfisca-us

- changelog.yaml
- policyengine-client/src/countries/us/us.jsx
> Hide US impact page

- changelog.yaml
- policyengine/utils/reforms.py
> Enable mixed parametric/structural reforms

- changelog.yaml
- policyengine-client/src/countries/us/us.jsx
- setup.py
> Use shorter End Child Poverty Act parameter names

- changelog.yaml
- policyengine/countries/us/__init__.py
> Disable state taxes on US impacts

- changelog.yaml
- policyengine-client/src/countries/us/us.jsx
- policyengine-client/src/policyengine/pages/household/inputPane.jsx
- policyengine-client/src/policyengine/pages/policy/overview.jsx
> Add adult dependents

- changelog.yaml
- policyengine-client/package.json
- policyengine-client/src/countries/country.jsx
- policyengine-client/src/countries/uk/uk.jsx
- policyengine-client/src/policyengine/pages/populationImpact/ageChart.jsx
- policyengine-client/src/policyengine/pages/populationImpact/populationImpact.jsx
- policyengine/countries/country.py
- policyengine/impact/population/charts.py
> Add age impact chart (optional)

- changelog.yaml
- policyengine-client/src/countries/us/us.jsx
- setup.py
Fixes #807 and updates openfisca-us
After adjusting the first two:
Ready to merge.
> Add EITC eligibility parameters

- changelog.yaml
- policyengine-client/package.json
- policyengine-client/src/countries/country.jsx
- policyengine-client/src/policyengine/general/help.jsx
- policyengine-client/src/policyengine/layout/general.jsx
> Fix footer

- changelog.yaml
- policyengine-client/src/countries/us/us.jsx
> Fix marital status

- policyengine-client/src/countries/us/us.jsx
Doing this should get us what we want
```
if ((status === "Married") && !situation.people.hasOwnProperty("Your spouse")) {
this.addPartner(situation);
} else if ((status === "Single") && situation.people.hasOwnProperty("Your spouse")) {
this.removePerson(situation, "Your spouse");
}
```
Fixes #813
> Bug fix better

- changelog.yaml
- policyengine-client/src/countries/us/us.jsx
- policyengine/countries/us/reform_parameters.yaml
- setup.py
> Update MA dependent care credit parameters

- changelog.yaml
- policyengine-client/src/countries/us/us.jsx
- policyengine/countries/us/reform_parameters.yaml
- setup.py
> Manually revert openfisca-us update

- Makefile
- changelog_entry.yaml
- policyengine/utils/reforms.py
- policyengine/utils/situations.py
Fixes #839 (but this time enabling OpenFisca-US to be updated). cc @MaxGhenis
> Fix slowdown root cause

- changelog_entry.yaml
- policyengine-client/src/countries/us/us.jsx
- policyengine-client/src/policyengine/pages/household/variable.jsx
- policyengine-client/src/policyengine/pages/policy/parameter.jsx
- policyengine/countries/country.py
- policyengine/utils/reforms.py
Fixes #777
Also adds MD income tax breakdowns.
> State code (MD) fixes

- changelog_entry.yaml
- policyengine-client/src/countries/us/us.jsx
> Add WA WFTC parameters

- changelog_entry.yaml
- policyengine-client/src/policyengine/pages/household/accountingTable.jsx
> Fix household impact calculator

- app.yaml
- changelog_entry.yaml
- policyengine-client/src/policyengine/pages/household/earningsCharts.jsx
- policyengine-client/src/policyengine/pages/populationImpact/ageChart.jsx
- policyengine-client/src/policyengine/pages/populationImpact/populationImpact.jsx
- policyengine/country/country.py
- policyengine/country/uk/uk.py
- policyengine/country/us/us.py
- policyengine/tests/us/state_specific.yaml
> Fix state-specific bug

- changelog_entry.yaml
- policyengine-client/src/policyengine/pages/household/earningsCharts.jsx
- policyengine-client/src/policyengine/pages/populationImpact/populationImpact.jsx
> Round ETAs to 15s

- changelog_entry.yaml
- policyengine-client/src/countries/us/us.jsx
- setup.py
> Bump OpenFisca US to capture WA WFTC update

- changelog_entry.yaml
- policyengine-client/src/policyengine/pages/populationImpact/populationImpact.jsx
Fixes #911
This PR only contains [one line](https://github.com/PolicyEngine/policyengine/pull/912/files#diff-29c1484177ebda7eedaf74700fbb3c8de69d75b0baf3d9ab2d831e0da552ca7aR254) of substantive changes.
(See https://github.com/PolicyEngine/policyengine/issues/122 for consistent jsx formatting to avoid these extraneous changes)
> Fix incorrect ETA on population impact page

- changelog_entry.yaml
- policyengine/country/us/additional_parameters.yaml
> Add US states without income tax

- changelog_entry.yaml
- policyengine-client/src/countries/us/us.jsx
- policyengine-client/src/policyengine/general/navigationButton.jsx
- policyengine-client/src/policyengine/header/title.jsx
- policyengine-client/src/policyengine/pages/policy/overview.jsx
> Center logo on mobile

- changelog_entry.yaml
- policyengine-client/src/policyengine/general/navigationButton.jsx
- policyengine-client/src/policyengine/pages/policy/overview.jsx
Fixes #803 
Policy overview shading on desktop is functional.
> Overview shading works

- changelog_entry.yaml
- policyengine-client/src/policyengine/header/socialLinks.jsx
> Update Facebook link

- changelog_entry.yaml
- policyengine-client/src/policyengine/pages/household/menu.jsx
Fixes #338
Font size for headings in the "Your Household" page was increased. The larger fonts make the different categories more noticeable. Let me know if we want to alter the size more, make them bold, or alter the subheadings.
> Bolded headings on Your Household

- changelog_entry.yaml
- policyengine-client/src/countries/country.jsx
- policyengine-client/src/countries/uk/uk.jsx
- policyengine/country/uk/additional_parameters.yaml
> Fix marriage allowance income condition bug

- changelog_entry.yaml
- policyengine-client/src/countries/uk/components/autoUBI.jsx
- policyengine-client/src/landing.jsx
- policyengine/country/country.py
- policyengine/impact/utils/text.py
> Fix AutoUBI and add blog posts

- changelog_entry.yaml
- policyengine-client/src/policyengine/pages/policy/parameter/parameter.jsx
- policyengine/country/openfisca/parameters.py
> Scale bug fix

- changelog_entry.yaml
- policyengine-client/src/countries/country.jsx
- setup.py
> Fix baseline editing refresh bug

- changelog_entry.yaml
- policyengine/country/openfisca/reforms.py
> Add extra safety checks for switches

- changelog_entry.yaml
- policyengine-client/src/countries/uk/components/timeTravel.jsx
- policyengine-client/src/countries/us/us.jsx
- policyengine/country/openfisca/parameters.py
- setup.py
> Add snapshot to US policy

- changelog_entry.yaml
- policyengine/country/us/additional_parameters.yaml
- setup.py
> Add New York to geographic drop-down

- changelog_entry.yaml
- policyengine/country/openfisca/reforms.py
> Fix NY CTC bug

- changelog_entry.yaml
- policyengine-client/src/countries/uk/uk.jsx
- policyengine/country/openfisca/reforms.py
- policyengine/country/uk/default_reform.py
- setup.py
Add each quarter, from Q4 2022 to Q3 2023.
> Add UK energy price cap

- changelog_entry.yaml
- policyengine-client/src/countries/country.jsx
- policyengine-client/src/countries/uk/components/timeTravel.jsx
- policyengine-client/src/countries/uk/uk.jsx
- policyengine-client/src/countries/us/us.jsx
- policyengine-client/src/countries/utils/timePeriod.jsx
- policyengine-client/src/policyengine/pages/household/accountingTable.jsx
- policyengine-client/src/policyengine/pages/household/variable.jsx
- policyengine-client/src/policyengine/policyengine.jsx
- policyengine/country/country.py
- policyengine/country/openfisca/reforms.py
- policyengine/country/uk/additional_parameters.yaml
- policyengine/country/uk/default_reform.py
- policyengine/country/uk/uk.py
- policyengine/country/us/default_reform.py
- policyengine/country/us/us.py
> Add policy date feature in UI

- changelog_entry.yaml
- policyengine-client/src/countries/us/us.jsx
Fixes #993 (I suspect also the indirect cause of some other recent issues, will check once merged).
cc @MaxGhenis
> Fix household input bug

- changelog_entry.yaml
- policyengine-client/src/countries/country.jsx
- policyengine-client/src/countries/uk/components/timeTravel.jsx
- policyengine-client/src/countries/uk/uk.jsx
- policyengine-client/src/countries/us/us.jsx
- policyengine-client/src/countries/utils/timePeriod.jsx
- policyengine-client/src/policyengine/pages/household/accountingTable.jsx
- policyengine-client/src/policyengine/pages/household/earningsCharts.jsx
- policyengine-client/src/policyengine/policyengine.jsx
- policyengine-client/src/policyengine/tools/url.jsx
- policyengine/country/country.py
- policyengine/country/openfisca/reforms.py
- policyengine/impact/household/charts/budget.py
> Fix URL policy date scraping

- changelog_entry.yaml
- policyengine-client/src/countries/us/us.jsx
> Remove duplicate net income entries for clean energy rebates

- changelog_entry.yaml
- policyengine-client/src/countries/uk/uk.jsx
- policyengine/country/country.py
- policyengine/country/openfisca/reforms.py
- setup.py
Requires https://github.com/PolicyEngine/openfisca-uk/pull/627
> Bump UK and ensure mid-year parameters uprate variables

- changelog_entry.yaml
- policyengine-client/src/countries/us/us.jsx
> Add missing benefits

- changelog_entry.yaml
- policyengine/impact/household/charts/budget.py
> Fix hovercard issue for baseline-only earnings charts

- changelog_entry.yaml
- policyengine/country/openfisca/reforms.py
> Fix baseline reform handling

- changelog_entry.yaml
- policyengine/country/openfisca/reforms.py
- policyengine/impact/household/charts/budget.py
> Fix baseline reforms

- changelog_entry.yaml
- policyengine-client/src/countries/country.jsx
- policyengine-client/src/countries/us/us.jsx
- policyengine-client/src/policyengine/pages/populationImpact/populationImpact.jsx
- policyengine/country/us/additional_parameters.yaml
Fixes #968 
Fixes #857 
Fixes #982 
Fixes #987
> Add Social Security repeal and inputs for unemployment and charitable donations

- changelog_entry.yaml
- policyengine-client/src/countries/us/us.jsx
- setup.py
> Add FPG basic income element

- changelog_entry.yaml
- policyengine-client/src/countries/uk/components/autoUBI.jsx
- policyengine-client/src/policyengine/policyengine.jsx
> Fix AutoUBI and parameter renames

- changelog_entry.yaml
- policyengine-client/src/countries/us/us.jsx
- setup.py
> Add flat per-person UBI parameter to US

- changelog_entry.yaml
- policyengine/country/openfisca/reforms.py
> Fix non-abolitions

- changelog_entry.yaml
- policyengine-client/src/countries/country.jsx
- policyengine-client/src/countries/us/us.jsx
- policyengine/country/us/additional_parameters.yaml
- policyengine/country/us/default_reform.py
> Add PTC exemption, enable Blank Slate reforms
