PolicyEngine/policyengine

- server/policyengine_core/server.py
Because the assets folder was passed into a now different package, the static assets wouldn't load and as of right now generate 404 errors that don't show up when debugging the client.
> Fix error causing static assets to fail to load

- client/policyengine-core/package.json
- client/policyengine-core/src/common/layout.jsx
Ensures both /household and /situation (legacy) point to the household input page (Resilience UBI calculator relies on this at the moment)
> Show header on legacy /situation page

- server/policyengine_core/server.py
- server/setup.py
This caused requests with no cached result to return None.
> Fix caching issue

- policyengine-client/package.json
- policyengine/countries/country.py
- policyengine/impact/population/metrics.py
- policyengine/server.py
- setup.py
I think this was caused by the chart calculating poverty rates a year ahead of the takeaway. I've fixed it by forcing all calculations to use the `default_year` argument rather than setting explicitly.
> Poverty bug fix

- policyengine-client/src/common/advanced.jsx
Does this require a version bump?
> Fix typo in tooltip

- policyengine-client/src/common/header.jsx
- policyengine/impact/population/breakdown.py
- policyengine/server.py
- policyengine/utils/reforms.py
- setup.py
Fixes an issue causing the decile chart colouring to malfunction (because multiple provisions had the same summary field).
Fixes #170 
Fixes #78 (summary metadata fields can be safely deleted in openfisca-uk after this - they are now ignored)
> Auto-generate summary field

- requirements.txt
The `requirements.txt` didn't match `setup.py` in its requirement for openfisca-us.
> Fix deployment error

- Makefile
- app.yaml
Attempts to fix the failing US build - the error was from a HDF5 "back error trace" when generating the `RawCPS` dataset. So I've gone with the UK approach and added the actual module `openfisca_us_data` to the deployment environment, after downloading the dataset before deployment.
> Add openfisca-us-data to deployment environment

- policyengine-client/src/common/parameter.jsx
> Fix decimal input

- policyengine/countries/country.py
- policyengine/countries/uk/__init__.py
This adds the default logic from the openfisca web api to policyengine, for the UK.
> Add UK /calculate endpoint

- Dockerfile
- Makefile
As anticipated, the GCP issue around cloud storage persisted. Adding the fix here.
> Add GAC fix

- policyengine-client/src/App.jsx
- policyengine-client/src/common/parameter.jsx
- policyengine-client/src/countries/uk/data/policy_controls.jsx
- policyengine/countries/uk/__init__.py
- policyengine/countries/uk/default_reform.py
- policyengine/countries/uk/reform_parameters.yaml
- setup.py
> Carbon Tax, Council Tax, taxable and means-test-included UBI

- policyengine-client/src/App.jsx
- policyengine-client/src/common/layout.jsx
- policyengine-client/src/data/namedPolicies.jsx
- policyengine/server.py
This adds a redirect for certain policies to their population impact page. For example, this PR adds:
* /uk/ubi-labs/covid-dividend -> /uk/population-impact/[Covid Dividend parameters]
* /uk/ubi-labs/resilience-ubi -> /uk/population-impact/[Resilience UBI parameters]
This is a first step, but might want to figure out the best way exactly to do this (currently, it's just a redirect, rather than an explicit naming of the reform (I looked into that, but seems it might be complex since a lot of the site relies on being able to check the URL contents). But one solution could be to do something like:
* /uk/population-impact/resilience-ubi = /uk/population-impact?parameter1=x...
* /uk/household/resilience-ubi = /uk/household?parameter1=x...
> Add named redirects

- policyengine-client/src/App.jsx
It's redirecting all pages to the Covid Dividend for some reason.
> Remove named policies for now

- policyengine-client/src/App.jsx
Learned my lesson about merging trivial changes without waiting for tests to pass - npm build requires formatting as well.
> Fix syntax

- policyengine-client/src/countries/uk/data/policy_controls.jsx
- policyengine/countries/uk/reform_parameters.yaml
> Remove Council Tax for now

- policyengine-client/src/common/url.jsx
In order to not have the URLs with `abolish_CT=2` break, we need to add a catch when scraping the URL to get the policy.
> Add catch for bad parameters

- policyengine-client/src/common/pages/populationImpact.jsx
> Fix boolean value bug

- policyengine-client/src/common/parameter.jsx
As above. Though yes @MaxGhenis I do agree on the extra click - in future, [this](https://ant.design/components/input-number/#components-input-number-demo-basic) might be a solution (`addonAfter`).
> Multiply rates by 100

- policyengine-client/src/App.jsx
- policyengine-client/src/common/header.jsx
- policyengine-client/src/common/overview.jsx
- policyengine-client/src/common/pages/household.jsx
- policyengine-client/src/countries/us/app.jsx
- policyengine-client/src/countries/us/data/policy.jsx
- policyengine-client/src/countries/us/data/situation.jsx
- policyengine-client/src/countries/us/index.jsx
- policyengine-client/src/countries/us/logic/policy.jsx
- policyengine-client/src/countries/us/logic/situation.jsx
- policyengine/countries/country.py
- policyengine/countries/us/__init__.py
This surfaces the US household page, with:
* Age
* State code
* Marital status
* School lunch subsidy
> Add PolicyEngine US (Household page)

- Makefile
- policyengine/countries/uk/default_reform.py
- policyengine/countries/uk/reform_parameters.yaml
This adds the formulas and parameters needed to estimate carbon consumption and land value exposure from other wealth and consumption data. This needs to be in ahead of #227 , because we only serve the latest dataset on GCP, and when https://github.com/PolicyEngine/openfisca-uk-data/pull/60 is merged, it will remove the carbon imputations, which will be done on OpenFisca UK's side from now on. Without this PR, that'll set the land values and carbon consumptions to zero.
> Add carbon and land formulas

- policyengine/__init__.py
> Bump version

- policyengine-client/src/common/pages/household.jsx
- policyengine-client/src/countries/uk/data/situation.jsx
Caused by a variable rename `expected_stamp_duty` -> `expected_sdlt`. Filed https://github.com/PolicyEngine/policyengine/issues/280
> Fix household calculations

- policyengine-client/src/countries/uk/data/policy.jsx
- policyengine/countries/uk/reform_parameters.yaml
- setup.py
Adds the business rates variable, depends on https://github.com/PolicyEngine/openfisca-uk/pull/413
> Add business rates

- policyengine-client/src/common/pages/household.jsx
- policyengine/utils/reforms.py
This should hopefully fix some phantom bugs I haven't been able to consistently reproduce - occasionally, the household impact fails to load. I've set the "view household impact" button to wait until household computations are done and made the reform parsing more robust.
> Improve stability on household impact

- policyengine-client/src/countries/uk/data/policy.jsx
- policyengine/countries/uk/default_reform/reform.py
- policyengine/countries/uk/reform_parameters.yaml
Adds a parameter to adjust the consumer (vs shareholder) incidence of carbon taxes. Defaults to 100%.
> Add household incidence

- Makefile
- README.md
- policyengine/countries/uk/__init__.py
This adds a way for everyone who doesn't have access to the UK microdata to run the server - it should work as described in the README (just changing a bool option from false to true).
> Add synthetic mode

- CHANGELOG.md
- README.md
- policyengine-client/package.json
- policyengine-client/src/countries/country.jsx
- policyengine-client/src/countries/uk/uk.jsx
- policyengine-client/src/countries/us/us.jsx
- policyengine/__init__.py
This PR adds an option in `country.jsx` for changes only involving the client - previously, the API URL was derived from the current URL (this is required for the beta site). I've added to the README specifying this.
> Add option for local client-only debugging

- CHANGELOG.md
- policyengine-client/package.json
- policyengine-client/src/countries/us/us.jsx
- policyengine/__init__.py
- setup.py
This adds the US policy page, dependent on https://github.com/PolicyEngine/openfisca-us/pull/475.
> Add US policy page

- CHANGELOG.md
- policyengine-client/package.json
- policyengine/__init__.py
- setup.py
Hopefully fixes the deployment error (from the error message, may be hiding another).
> Fix deployment failure

- CHANGELOG.md
- policyengine-client/src/countries/country.jsx
- policyengine-client/src/countries/us/us.jsx
- policyengine/__init__.py
- setup.py
Adds more inputs to the US screen to improve SNAP calculation and update to the latest version of OpenFisca-US, which improves SNAP calculations. Specifically it includes:
* Earned income sources: employment & self-employment income
* Unearned income sources: dividend & interest income
* Medical expense deduction inputs: medical out of pocket expenses
* Inputs for special disability rules: SSDI, SSI disabled, and disabled veteran status or family member
* Categorical eligibility inputs: SSI
* Shelter deduction inputs: housing costs and homelessness
* Dependent care deduction inputs: childcare expenses (NB: this doesn't look good because we need units, see PolicyEngine/openfisca-us#496)
I omitted `spm_unit_assets` because we don't have stocks/flows yet in openfisca-us (to my knowledge?) …
> Add SNAP inputs and update openfisca-US

- CHANGELOG.md
- policyengine-client/package.json
- policyengine-client/src/countries/country.jsx
- policyengine-client/src/countries/us/us.jsx
- policyengine-client/src/policyengine/pages/household/inputPane.jsx
- policyengine/__init__.py
@MaxGhenis it turned out to be because the flag for "show household people selector" was misnamed on the UK (page failed completely) and missing on the US (just the household people selector didn't display).
> Household-reorganise

- CHANGELOG.md
- policyengine-client/src/countries/country.jsx
- policyengine-client/src/countries/uk/uk.jsx
- policyengine-client/src/policyengine/tools/namedPolicies.jsx
- policyengine/__init__.py
- policyengine/countries/uk/reform_parameters.yaml
- setup.py
Fixes #403 
Fixes #404 
Fixes #405
> UC parameters and Green Party manifesto

- CHANGELOG.md
- policyengine-client/package.json
- policyengine-client/src/countries/uk/uk.jsx
- policyengine/__init__.py
- policyengine/countries/uk/default_reform/reform.py
- policyengine/countries/uk/reform_parameters.yaml
> Add misc. cash payments

- .github/workflows/push.yml
Trying to get around the branch protection rules, only for the version bump action.
> Add credentials to version bump action

- .github/workflows/push.yml
Nearly there I think- just need to ensure we don't end up in an infinite loop of GH actions after creating a bump version commit.
> Add conditionals to push action

- changelog.yaml
Testing the new changelog automatic features.
> Add changelog entry

- changelog.yaml
- policyengine/impact/population/charts.py
> add baseline/reform values to inequality chart hover cards

- changelog.yaml
- policyengine-client/src/countries/uk/uk.jsx
Fixes a bug in which adding a spouse wouldn't add their age to 2022 (appearing as "null")
> Marriage bug

- changelog.yaml
- setup.py
The previous PR didn't correctly update OpenFisca-US.
> Bump openfisca-us

- changelog.yaml
- policyengine-client/src/countries/country.jsx
- policyengine/countries/uk/__init__.py
- policyengine/countries/us/__init__.py
- policyengine/impact/household/charts.py
- policyengine/impact/population/breakdown.py
- policyengine/impact/population/charts.py
- policyengine/utils/charts.py
- policyengine/utils/general.py
> Use USD in US charts

- changelog.yaml
- policyengine-client/package.json
- policyengine-client/public/index.html
- policyengine-client/src/App.jsx
- policyengine-client/src/landing.jsx
- policyengine-client/src/policyengine/header/mainNavigation.jsx
- policyengine/countries/country.py
- policyengine/tests/server/situations/test_calculate_endpoint.py
- setup.py
> Fix API bug

- changelog.yaml
- policyengine-client/package.json
- policyengine-client/src/App.jsx
- policyengine-client/src/countries/country.jsx
- policyengine-client/src/countries/uk/components/faq.md
- policyengine-client/src/countries/uk/uk.jsx
- policyengine-client/src/landing.jsx
- policyengine-client/src/markdown/uk/faq.md
- policyengine-client/src/policyengine/pages/household/accountingTable.jsx
- policyengine-client/src/policyengine/pages/household/earningsCharts.jsx
- policyengine-client/src/policyengine/pages/populationImpact/chart.jsx
- policyengine-client/src/policyengine/policyengine.jsx
- policyengine-client/src/policyengine/tools/translation.jsx
- policyengine/countries/country.py
- policyengine/utils/reforms.py
- 50-70% speed increase in simulations.
- Broken IFrame removed from FAQ pages.
- Blog subtitle removed.
> Performance improvements and bug fixes

- changelog.yaml
- policyengine-client/src/landing.jsx
I think the issue is our API to access the Medium blog feed changed or broke. In the meantime, this replaces the posts with an empty list to ensure the site itself stays up. 
Site crash reproduced locally and fixed locally within this PR.
> Resurrect policyengine.org

- changelog.yaml
- policyengine/impact/household/charts.py
Fixes #565 
Fixes #646
Example (this one happens to look off because of a rounding error):
> Improve decimals in MTR chart

- app.yaml
- changelog.yaml
It turns out we can have a maximum of 6.5GB per CPU on gcloud, so we'd need to add an extra CPU. But I'm not sure we need to, as I think the memory requirement mentioned in #671 was a misdiagnosis and https://github.com/PolicyEngine/openfisca-us/pull/709 fixed the actual issue.
> Revert memory increase

- changelog.yaml
- policyengine/utils/situations.py
This was introduced by me about two hours ago, when adding the descriptions to the API explorer. It affects variables without a description provided (they get incorrectly assigned the last successfully loaded descriptions).
> Fix descriptions bugs

- changelog.yaml
- policyengine-client/src/countries/country.jsx
- policyengine/impact/household/charts.py
Fixes #697 
For example, this reform enlarges a cliff for a household with broadband costs: 
A few things left to do:
> Shade cliff regions in net income and MTR charts

- changelog.yaml
- policyengine-client/src/policyengine/pages/policy/parameter.jsx
- policyengine-client/src/style/policyengine.less
Makes breakdown parameters borderless, and fix the capitalised breakdown names in the MA section.
> Breakdown parameter improvements

- policyengine-client/src/countries/us/us.jsx
1. Visit [PolicyEngine US Household page](https://policyengine.org/us/household)
2. Switch from Single to Married
3. Go to one of the People menus, e.g. Income
4. Return to the Household > People menu
fixes #813
> Bug fix: Married status in US

- .github/workflows/push.yml
cc @MaxGhenis - this should fix redeployments for all commits after this is merged.
> Don't publish to NPM if version is lower than latest

- changelog_entry.yaml
- policyengine-client/src/countries/country.jsx
- policyengine-client/src/policyengine/tools/url.jsx
cc @MaxGhenis 
Fixes a bug that causes baseline-editing policies to show as no-reforms.
> Fix URL bug

- changelog_entry.yaml
- policyengine-client/src/policyengine/pages/household/household.jsx
- policyengine-client/src/policyengine/pages/policy/overview.jsx
- policyengine-client/src/policyengine/pages/policy/policy.jsx
- policyengine-client/src/policyengine/pages/populationImpact/populationImpact.jsx
Fixes #921
- Right panel shading touches the header and right viewport.
- Change is visable on all three tabs of impact as well as both US and UK versions.
> Right shading panel adjusted

- changelog_entry.yaml
- policyengine-client/src/policyengine/pages/policy/overview.jsx
Fixes #922.
Items inside the policy cart are now separated by bold titles and small descriptions. Let me know if we want to change the spacing, font size, or boldness.
> Removes bullet graphic in policy cart

- changelog_entry.yaml
- policyengine-client/src/policyengine/pages/household/variable.jsx
Fixes #757
- Spacing has been adjusted for both the selected and drop-down menu in State Codes.
- A border has been added around the selected state to improve visability.
> Adjusted spacing in state code drop-down

- changelog_entry.yaml
- policyengine-client/src/policyengine/pages/household/menu.jsx
- policyengine-client/src/policyengine/pages/policy/menu.jsx
- policyengine-client/src/policyengine/pages/policy/overview.jsx
Update to #471 .
Policy and Your Household menus have been given padding to support a better UX when scrolling.
- Prior to this PR, if the viewheight was smaller than the menu height, the last child in the menu was cut off by the footer (image 1).
- Now, the entire column has been given bottom padding to facilite the last child (image 2).
- Policy Overview and menus now have the same hex color (image 3).
> Padding added to support scrolling

- changelog_entry.yaml
- policyengine-client/src/policyengine/pages/policy/overview.jsx
Fixes #784 
Style for pagination in the policy cart was changed from "Simple" to "Controlled." This change allows for easier centering and navigation to the different pages.
The number of pages that appear are determined by the number of items in the cart and the width of the policy cart. Pagination iteself does not overflow the policy cart container.
> Centering pagination in policy cart

- changelog_entry.yaml
- policyengine-client/src/countries/uk/uk.jsx
> Fix Scottish rates policy menu crashing the app

- changelog_entry.yaml
- policyengine-client/src/countries/us/us.jsx
- setup.py
Fixes #957 and fixes #961
Locally, the How earnings affect you chart spins forever when toggling either the AGI limit or the dollar-defined phase-out range, but everything else works right so going to merge this and debug that separately.
> Display new BI parameters: AGI limit and dollar-defined phase-out range

- changelog_entry.yaml
- policyengine/country/country.py
Ensures that situations defined with [axes](https://openfisca.org/doc/simulate/replicate-simulation-inputs.html) work on `/calculate`.
> Add axis handling for `/calculate`

- changelog_entry.yaml
- policyengine-client/src/countries/us/us.jsx
- setup.py
Fixes #1006
After bumping the requirements and running `make install`, the server is throwing this error after computing the population impact:
>  [2022-09-13T12:47:56.817818] event: task_error endpoint: population_reform error: "Unable to open object (object 'marital_unit_id' doesn't exist)" full_trace: Traceback (most recent call last):
> Add US basic income taxability

- changelog_entry.yaml
- policyengine-client/src/policyengine/pages/policy/menu.jsx
Fixes #973.
- Menu items now word wrap when their name is cut short by the right border.
- This patch is applied to all levels in the policy menu.
> Word wrap to menu items

- changelog_entry.yaml
- policyengine-client/src/countries/country.jsx
This change wasn't caught because usually I avoid staging changes to `country.jsx`: in this case, there was a one-liner by the last PR that was needed to avoid breaking a page.
> Fix US pages

- changelog_entry.yaml
- policyengine-client/src/policyengine/header/title.jsx
Fixes #946.
- Top PolicyEngine logo is now centered in both US and UK.
> Mobile PolicyEngine logo is now centered in both countries

- changelog_entry.yaml
- policyengine-client/src/policyengine/pages/policy/overview.jsx
Fixes #1034.
Policy Cart items are now centered on Desktop.
> Policy Cart items are now centered on desktop

- changelog_entry.yaml
- policyengine-client/src/policyengine/pages/policy/parameter/parameter.jsx
Fixes #604 
- Dropdown menus through the app now show all options without being cutoff.
- This patch is effective in both desktop and mobile viewports.
> Adjusted drop-down menus to text-width maximum

- changelog_entry.yaml
- policyengine-client/src/policyengine/pages/household/accountingTable.jsx
Fixes #609 
- Numbers on the net-income table are now aligned to the right. 
- An extra column was added to the end of the table to provide padding and preserve the upper-right border-radius.
> right-align numbers in net income table
